### ISSUE TITLE
課題0517の4問目への質問

### ISSUE THREAD

**Issue by Ymgc19** [lvzeyu/chss_2023_assignment#17]
課題0517の4問目の意味がよくわかりません．
名前と出生年のそれぞれのリストを作成し，それをsortするという問題ですか？

**Comment by Ymgc19** [comment]
それと今日の夕方から，課題の回答をpull requestしようとしているのですが，延々とpull requestのロードが終わりません．3回試しましたが，3回ともpull requestが完了しませんでした．今までこんなことはなかったのですが，何が原因と考えられますか？

**Comment by lvzeyu** [comment]
ここで値は`{key:value}`におけるのvalueを指していますので、生まれた年をリストにして、sortする操作をやってください。

**Comment by lvzeyu** [comment]
> それと今日の夕方から，課題の回答をpull requestしようとしているのですが，延々とpull requestのロードが終わりません．3回試しましたが，3回ともpull requestが完了しませんでした．今までこんなことはなかったのですが，何が原因と考えられますか？

何らかのError messageが表示されましたか？

**Comment by Ymgc19** [comment]
> > それと今日の夕方から，課題の回答をpull requestしようとしているのですが，延々とpull requestのロードが終わりません．3回試しましたが，3回ともpull requestが完了しませんでした．今までこんなことはなかったのですが，何が原因と考えられますか？
> 
> 何らかのError messageが表示されましたか？

Pull request creation failed. Validation failed: was submitted too quickly と出ました．一晩経過したらたぶん解決したと思います．
